# http://www.appveyor.com/docs/appveyor-yml

# Be aware of https://github.com/nodejs/LTS when choosing versions to test
# Update engines.node in package.json if removing old versions.
environment:
  matrix:
    - nodejs_version: "6"
      npm_version: "latest"
      # Empty version installs most recent version available
    - nodejs_version: ""
      npm_version: "latest"

# If the package has arch-dependent features, uncomment this.
#platform:
#  - x86
#  - x64

install:
  - ps: Install-Product node $env:nodejs_version
  - npm -g install "npm@%npm_version%"
  # Ignore package-lock.json.  This is done for a few reasons:
  # - To test against current versions of dependencies.
  # - To test installability for dependents (doesn't use package-lock.json).
  - if exist package-lock.json del package-lock.json
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

# Disable build step, which we don't need
build: off

# If any job fails, fail build immediately to avoid wasting time/resources.
matrix:
  fast_finish: true
